#!/usr/bin/env bash
#Get the directory you ran the script from
IMAGE_PWD="$(pwd)"
cd -- "$OWD" 1>&2
count=0
argv () {
    SKIP_NEXT=0
    for i in "$@"; do
        arg="$i"
        if [ "$APPIMAGE_DEBUG" ]; then printf "Got Arg:       %s is ‘%s’\n" $count "$i" 1>&2; fi
        count=$(($count+1))
        first_letter=$(printf %.1s "$arg")
        if [[ "$arg" == "-e" || "$arg" == "--output=" ]]; then SKIP_NEXT=$(($SKIP_NEXT+1)); fi
        if [[ $first_letter != '-' && $SKIP_NEXT -lt 1 ]]; then
            arg=$(readlink -f "$arg")
        fi
        NEWARGS[$count]="$arg"
    done
}
debug () {
    temp_j=0
    for a in "${NEWARGS[@]}" ; do
        printf "Passing on Arg $temp_j is ‘%s’\n" "$a" 1>&2
        temp_j=$((temp_j+1))
    done
    if [ $temp_j == 0 ]; then printf "Did not see any command line args\n" 1>&2; fi
}
argv "$@"

if [ "$APPIMAGE_DEBUG" ]; then
    debug;
    printf "Changing directory to $IMAGE_PWD\n" 1>&2
fi
cd -- "$IMAGE_PWD" 1>&2
exec ./bin/moar  --execname="$0" --libpath="./share/nqp/lib" --libpath="./share/nqp/lib" \
--libpath="./share/perl6/lib" \
--libpath="./share/perl6/runtime" \
./share/perl6/runtime/perl6.moarvm \
"${NEWARGS[@]}"
